import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UrlMasker from "./UrlMasker"; // ✨ แก้เป็นจุดเดียวแล้ว เพื่อให้อ่านไฟล์ระดับเดียวกันได้ถูกต้อง

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UrlMasker /> {/* ซ่อน Path เงียบ ๆ อยู่เบื้องหลัง */}
        {children}
      </body>
    </html>
  );
}